---
- name: configure primary network
  template: src=ifcfg-eth1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-eth1

- name: configure secondray network
  template: src=ifcfg-eth1:1.j2  dest=/etc/sysconfig/network-scripts/ifcfg-eth1:1
