---
- name: Install Computational Nodes
  hosts: scc
  accelerate: true
  user: root

  roles:
    #- common   
    #- networking
    #- users     
    #- packages   
    - ganglia
    #- power 
    #- gluster
    #- nvidia


- name: Install Head-node only things
  hosts: scc-head
  user: root
  roles:
    - gmetad
    - opensm
