---
- name: Install Computational Nodes
  hosts: scc
  user: root

  roles:
    #- common   
    - networking
    #- users     
    #- packages   
    #- ganglia


- name: Install Head-node only things
  hosts: scc-head
  user: root
  roles:
    - opensm
    #- gmetad
