---
- name: Install Basic Packages
  yum: name="{{ item}}" state=installed
  with_items:
    - openssh-clients
    - htop
    - vim
    - bash-completion
    - "@Development tools"
    - "@Infiniband support"
    - infiniband-diags
    - man
    - man-pages
    - pciutils
    - wget
    - ntp
    - mvapich2-devel
    - lapack-devel
    - hwloc-devel
    - netcdf-devel
    - nano
    - bridge-utils


#- name: Install Packages from RPMs
  #yum:  name="{{ }}" state=installed
  #with_items:
    #- rpms/slurm-2.6.3.el6.x86_64.rpm

#- name: Enable RDMA service
  #service: name=rdma state=started enabled=true

#- name: Enable NTP
  #service: name=ntpd state=started enabled=true

