#!/bin/sh

# chkconfig: 2345 85 20
# description: Run dynamic CPU speed daemon and/or load appropriate

PERF=/usr/sbin/ib_perf.py
RETVAL=0

. /etc/rc.d/init.d/functions

case "$1" in
    start)
        echo -n "Starting ib_perf: "
	[ -f $PERF ] || exit 1
        daemon --pidfile /var/run/ibstat.py.pid $PERF
        echo
        RETVAL=$?
        ;;
    stop)
        echo -n "Shutting down ib_perf: "
        killproc -p /var/run/ibstat.py.pid ib_perf.py
        echo
        ;;
    restart)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
    status)
        status -p /var/run/ibstat.py.pid ib_perf.py
	;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $RETVAL
