---
#- name: Install Slurm packages
  #yum: name="{{ item}}" state=installed
  #with_items:
    #- /opt/vol/rpms/slurm-plugins-2.6.3-1.el6.x86_64.rpm
    #- /opt/vol/rpms/slurm-2.6.3-1.el6.x86_64.rpm
    #- /opt/vol/rpms/slurm-munge-2.6.3-1.el6.x86_64.rpm

- name: create munge user
  user: name=munge system=yes createhome=no uid=497

- name: create munge group
  group: name=munge system=yes gid=497

- name: create slurm user
  user: name=slurm system=yes createhome=no uid=496

- name: create slurm group
  group: name=slurm system=yes gid=496

- name: Copy munge.key
  copy: src=munge.key dest=/etc/munge/munge.key
  notify: restart munge

- name: ensure munge.key permissions
  file: path=/etc/munge/munge.key owner=munge group=munge mode=600

- name: Copy slurm.conf
  copy: src=slurm.conf dest=/etc/slurm/slurm.conf
  notify: restart slurm

- name: Copy gres.conf
  copy: src=gres.conf dest=/etc/slurm/gres.conf
  notify: restart slurm

- name: Enable munge
  service: name=munge state=started enabled=true

- name: Enable Slurm
  service: name=slurm state=started enabled=true

