---
- name: Create RPM directory
  file: path=/tmp/rpms state=directory

- name: Copy Ganglia RPMs
  copy: src="{{ item}}" dest="/tmp/{{ item}}"
  with_items:
    - rpms/libganglia-3.6.0-1.x86_64.rpm
    - rpms/ganglia-gmond-3.6.0-1.x86_64.rpm
    - rpms/ganglia-gmond-modules-python-3.6.0-1.x86_64.rpm

- name: Install Ganglia RPMs
  yum: name="{{ item}}" state=installed
  with_items:
      - /tmp/rpms/libganglia-3.6.0-1.x86_64.rpm
      - /tmp/rpms/ganglia-gmond-3.6.0-1.x86_64.rpm
      - /tmp/rpms/ganglia-gmond-modules-python-3.6.0-1.x86_64.rpm

- name: Copy config file
  copy: src=gmond.conf dest=/etc/ganglia/gmond.conf

- name: Enable gmond daemon
  service: name=gmond state=started enabled=true

- name: Copy ib_perf.py
  copy: src=ib_perf.py dest=/usr/sbin/ib_perf.py mode=755

- name: Copy ib_perf rc file
  copy: src=ib_perf dest=/etc/init.d/ib_perf mode=755

- name: Enable and start ib_perf service
  service: name=ib_perf state=started enabled=true

