---
- name: Create mgabed
  user: name=mgabed group=users groups=wheel uid=500
- name: Create jaleman
  user: name=jaleman group=users groups=wheel uid=501
- name: Create seaker
  user: name=seaker group=users groups=wheel uid=502
- name: Create johnJoseph
  user: name=johnJoseph group=users groups=wheel uid=503
- name: Create benhavey
  user: name=benhavey group=users groups=wheel uid=504
- name: Create rh
  user: name=rh group=users groups=wheel uid=505
- name: Create nhentschel
  user: name=nhentschel group=users uid=506
- name: Create jnfurst
  user: name=jnfurst group=users groups=wheel uid=507

- name: copy over mgabed ssh key
  authorized_key: user=mgabed key="{{ item}}"
  with_file:
     - mgabed.pub
     - michael.pub

- name: copy over jaleman ssh key
  authorized_key: user=jaleman key="{{ item}}"
  with_file:
     - jaleman.pub
     - jaleman2.pub
     - jaleman3.pub

- name: copy over seaker ssh key
  authorized_key: user=seaker key="{{ item}}"
  with_file:
     - seaker.pub

- name: copy over johnJoseph ssh key
  authorized_key: user=johnJoseph key="{{ item}}"
  with_file:
     - mnijohn.pub
     - mnijohn2.pub
     - mnijohn3.pub
     - mnijohn4.pub

- name: copy over benhavey ssh key
  authorized_key: user=benhavey key="{{ item}}"
  with_file:
    - benhavey.pub

- name: copy over rh ssh key
  authorized_key: user=rh key="{{ item}}"
  with_file:
    - rh.pub

- name: copy over nhentschel ssh key
  authorized_key: user=nhentschel key="{{ item}}"
  with_file:
    - nhentschel.pub

- name: copy over jnfurst ssh key
  authorized_key: user=jnfurst key="{{ item}}"
  with_file:
    - jnfurst.pub
