---
- copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
- copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Allow wheel to sudo
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

- name: copy hosts file
  copy: src=hosts dest=/etc/hosts

- name: set limits
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: Add user keys to root
  authorized_key: user=root key="{{ item}}"
  with_file:
    - mgabed.pub
    - michael.pub
    - mnijohn.pub
    - mnijohn2.pub
    - seaker.pub
    - benhavey.pub
    - rh.pub


